# Generated by Django 3.2.16 on 2022-11-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='issuelist',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.equipment'),
        ),
        migrations.AddField(
            model_name='issuelist',
            name='flashes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuelist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
